stages:
  - release

.release_template: &release_definition
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $REGISTRY_PASSWORD registry.gitlab.com
    - docker info | grep Registry
    - apk add --no-cache python py-pip git
    - pip install python-magic
    - apk --purge del py-pip


release-image-and-deploy:
  <<: *release_definition
  stage: release
  script:
    - docker build -t registry.gitlab.com/delia-inc/colocation-senior .
    - docker push registry.gitlab.com/delia-inc/colocation-senior
    - curl -X POST https://portainer.delia.ovh/api/webhooks/5183ef35-84a8-44d8-bc72-8cfb9be2ac04
  only:
    - master
  when: manual
  tags:
    - docker
